#!/bin/sh

if [ "$#" -le 2 ]; then
    if [ "$#" -eq 0 ]; then
        echo "Please specify the type of the choices."
    elif [ "$#" -eq 1 ]; then
        echo "Please specify either \"a\" or \"an\" based on the choice type."
    else
        echo "No $1s to choose from."
        exit
    fi
    exit 1
fi

type="$1"
pref="$2" # a or an
shift 2

list_choices() {
    echo "The following ${type}s are available:"
    for i in `seq $#`; do
        printf "(%s)\t%s\n" "$i" "$1"
        shift
    done
}

list_choices "$@"

echo -n "Please select $pref $type: "
IFS= read choice

number_regex='^-?[0-9]+$'

while true; do
    if [ "$choice" -eq "$choice" ] 2> /dev/null; then
        if [ "$choice" -le 0 ] || [ "$choice" -gt "$#" ]; then
            echo "Invalid $type. Index must be >= 1 and <= $#."
            choice=
        else
            shift $((choice - 1))
            choice=$1
        fi
    elif [ -n "$choice" ]; then
        found=
        for c in "$@"; do
            if [ "$choice" = "$c" ]; then
                found=1
                break
            fi
        done
        if [ -z "$found" ]; then
            choice=
        fi
    fi

    if [ -n "$choice" ]; then
        echo $choice >&2
        break
    fi

    echo -n "Come again? "
    IFS= read choice
done
