#!/bin/zsh

if [ -z "$1" ]; then
    echo Please specify a filename to pack into.
    return
fi

local already_zipped=
if [ -f "$1" ]; then
    already_zipped=$(zipinfo -1 "$1" | sed 's/^/.\//')
fi
already_zipped=(${=already_zipped})
local folders=(.)
local files=()
while [ -n "$folders" ]; do
    loop_folders=$folders
    folders=()
    for folder in ${=loop_folders}; do
        local local_files=$(find $folder -type f -maxdepth 1)
        for f in ${=local_files}; do
            if (($already_zipped[(Ie)$f])); then
                continue
            fi

            decision_made=
            skip_rest=
            echo -n "Found file $f. Pack up? "
            while [ -z "$decision_made" ]; do
                read -sk 1
                if [[ $REPLY =~ ^[Yy]$ ]]; then
                    files+=($f)
                    decision_made=1
                    echo File will be included.
                elif [[ $REPLY =~ ^[Nn[:space:]]$ ]]; then
                    decision_made=1
                    echo File will be excluded.
                elif [[ $REPLY =~ ^[Vv]$ ]]; then
                    vi $f
                elif [[ $REPLY =~ ^[QqXx]$ ]]; then
                    echo
                    return
                elif [[ $REPLY =~ ^[Ss]$ ]]; then
                    skip_rest=1
                    echo
                    break
                fi
            done

            if [ -n "$skip_rest" ]; then
                break
            fi
        done

        local local_folders=$(find $folder -type d ! -path $folder -maxdepth 1)
        for f in ${=local_folders}; do
            decision_made=
            skip_rest=
            echo -n "Found folder $f. Pack up? "
            while [ -z "$decision_made" ]; do
                read -sk 1
                if [[ $REPLY =~ ^[Yy]$ ]]; then
                    files+=($f)
                    decision_made=1
                    echo Folder will be included.
                elif [[ $REPLY =~ ^[Nn[:space:]]$ ]]; then
                    decision_made=1
                    echo Folder will be excluded.
                elif [[ $REPLY =~ ^[Ll]$ ]]; then
                    echo
                    ls $f
                    echo -n "Found folder $f. Pack up? "
                elif [[ $REPLY =~ ^[Rr]$ ]]; then
                    folders+=($f)
                    decision_made=1
                    echo Folder will be recursed into.
                elif [[ $REPLY =~ ^[QqXx]$ ]]; then
                    echo
                    return
                elif [[ $REPLY =~ ^[Ss]$ ]]; then
                    skip_rest=1
                    echo
                    break
                fi
            done

            if [ -n "$skip_rest" ]; then
                break
            fi
        done
    done
done

if [ -z "$files" ]; then
    echo No files to pack up.
else
    zip -r $1 ${=files}
    echo Zipped and ready to go.
fi
