#!/bin/zsh

real() {
    pushd $(git rev-parse --show-toplevel) > /dev/null
    for i in $@; do
        realpath $i
    done
    popd > /dev/null
}

options -e "-s "<(echo ']c')"" "$(real $(git diff --name-only HEAD))"
